// 해외 고전 — 북스타 등록 데이터 (자동생성: 클레버/_gen_classics_foreign_data.py)
// 표지=제목만(텍스트), 본문=Supabase classics(origin='foreign') fetch(id=gb-{gutenberg_id})
// 옛 mvp35 해외와 겹치는 번호는 제외(옛 카드 메타 유지)
// 총 255권
const BOOKS_CLASSICS_FOREIGN = [
 {
  "id": "gb-791",
  "title": "The Princess",
  "author": "A. 테니슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 181,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6074",
  "title": "Lady Clare",
  "author": "A. 테니슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-70950",
  "title": "In memoriam",
  "author": "A. 테니슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-71178",
  "title": "Dora",
  "author": "A. 테니슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-217",
  "title": "Sons and Lovers",
  "author": "D. H. 로렌스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-22475",
  "title": "Tortoises",
  "author": "D. H. 로렌스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-59848",
  "title": "Kangaroo",
  "author": "D. H. 로렌스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 114,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-67915",
  "title": "Sun",
  "author": "D. H. 로렌스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31377",
  "title": "Weird Tales. Vol. 1 (of 2)",
  "author": "E.T.A. 호프만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31439",
  "title": "Weird Tales, Vol. 2 (of 2)",
  "author": "E.T.A. 호프만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31668",
  "title": "The Serapion Brethren, Vol. II",
  "author": "E.T.A. 호프만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31820",
  "title": "The Serapion Brethren, Vol. I.",
  "author": "E.T.A. 호프만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-805",
  "title": "This Side of Paradise",
  "author": "F. 스콧 피츠제럴드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6695",
  "title": "Tales of the Jazz Age",
  "author": "F. 스콧 피츠제럴드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 58,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-64317",
  "title": "The Great Gatsby",
  "author": "F. 스콧 피츠제럴드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "coverSrc": "./covers/gb-64317.webp",
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-68229",
  "title": "All the Sad Young Men",
  "author": "F. 스콧 피츠제럴드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31305",
  "title": "Atta Troll",
  "author": "H.하이네",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31726",
  "title": "Poems and Ballads of Heinrich Heine",
  "author": "H.하이네",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-37478",
  "title": "The Prose Writings of Heinrich Heine",
  "author": "H.하이네",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-65683",
  "title": "\"A Most Unholy Trade,\" Being Letters on the Drama by Henry James",
  "author": "H.하이네",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4661",
  "title": "Madame Aubin",
  "author": "P. 베를렌",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8426",
  "title": "Poems of Paul Verlaine",
  "author": "P. 베를렌",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 52,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14082",
  "title": "Le Corbeau = The Raven",
  "author": "S. 말라르메",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8801",
  "title": "Drum-Taps",
  "author": "W.휘트먼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-13182",
  "title": "Prefaces and prologues to famous books",
  "author": "W.휘트먼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-60505",
  "title": "Memories of Lincoln",
  "author": "W.휘트먼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1290",
  "title": "Salammbo",
  "author": "귀스타브 플로베르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-25014",
  "title": "Bouvard and Pécuchet: A Tragi-comic Novel of Bourgeois Life, part 1",
  "author": "귀스타브 플로베르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-27575",
  "title": "Madame Bovary: A Tale of Provincial Life, Vol. 1 (of 2)",
  "author": "귀스타브 플로베르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3664",
  "title": "Yvette",
  "author": "기 드 모파상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3804",
  "title": "Pierre and Jean",
  "author": "기 드 모파상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4777",
  "title": "Strong as Death",
  "author": "기 드 모파상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 57,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4788",
  "title": "Mademoiselle Fifi",
  "author": "기 드 모파상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 59,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-60771",
  "title": "The Poet Assassinated",
  "author": "기욤 아폴리네르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8868",
  "title": "Botchan (Master Darling)",
  "author": "나쓰메 소세키",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 62,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-73131",
  "title": "Unhuman tour",
  "author": "나쓰메 소세키",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-77",
  "title": "The House of the Seven Gables",
  "author": "너새니얼 호손",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 130,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7085",
  "title": "Fanshawe",
  "author": "너새니얼 호손",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 52,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-9222",
  "title": "A Select Party",
  "author": "너새니얼 호손",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-12060",
  "title": "The German Classics of the Nineteenth and Twentieth Centuries, Volume 04 Masterpieces of German Literature Translated into English. in Twenty Volumes",
  "author": "노발리스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 89,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31873",
  "title": "Henry of Ofterdingen: A Romance.",
  "author": "노발리스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3735",
  "title": "The Inspector-General",
  "author": "니콜라이 고골",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-58409",
  "title": "Cossack Tales",
  "author": "니콜라이 고골",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1004",
  "title": "Divine Comedy, Longfellow's Translation, Complete",
  "author": "단테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 37,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1008",
  "title": "Divine Comedy, Cary's Translation, Complete",
  "author": "단테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8800",
  "title": "The divine comedy",
  "author": "단테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-12867",
  "title": "The Banquet (Il Convito)",
  "author": "단테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-34544",
  "title": "This is not a story",
  "author": "드니 디드로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-54672",
  "title": "Les Bijoux Indiscrets, or, The Indiscreet Toys",
  "author": "드니 디드로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-38594",
  "title": "Poems",
  "author": "라이너 마리아 릴케",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-45605",
  "title": "Auguste Rodin",
  "author": "라이너 마리아 릴케",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-689",
  "title": "The Kreutzer Sonata and Other Stories",
  "author": "레프 니콜라예비치 톨스토이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 187,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2637",
  "title": "Youth",
  "author": "레프 니콜라예비치 톨스토이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-343",
  "title": "Fables",
  "author": "로버트 루이스 스티븐슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-413",
  "title": "Ballads",
  "author": "로버트 루이스 스티븐슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 172,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-421",
  "title": "Kidnapped",
  "author": "로버트 루이스 스티븐슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 171,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5436",
  "title": "Hyperion",
  "author": "롱펠로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-10490",
  "title": "The Golden Legend",
  "author": "롱펠로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-44398",
  "title": "Poems on Slavery",
  "author": "롱펠로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7178",
  "title": "Swann's Way",
  "author": "마르셀 프루스트",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 55,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-63532",
  "title": "Within a Budding Grove",
  "author": "마르셀 프루스트",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-73425",
  "title": "The Guermantes Way",
  "author": "마르셀 프루스트",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3177",
  "title": "Roughing It",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3186",
  "title": "The Mysterious Stranger, and Other Stories",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-60900",
  "title": "Merry Tales",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14636",
  "title": "Tragic Sense Of Life",
  "author": "미겔 데 우나무노",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-71260",
  "title": "Essays and soliloquies",
  "author": "미겔 데 우나무노",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-913",
  "title": "A Hero of Our Time",
  "author": "미하일 유리예비치 레르몬토프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1245",
  "title": "Night and Day",
  "author": "버지니아 울프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5670",
  "title": "Jacob's Room",
  "author": "버지니아 울프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-63230",
  "title": "Two Stories",
  "author": "버지니아 울프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-71865",
  "title": "Mrs. Dalloway",
  "author": "버지니아 울프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-36098",
  "title": "The Flowers of Evil",
  "author": "보들레르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-36620",
  "title": "The Three Hills, and Other Poems",
  "author": "보들레르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-47075",
  "title": "Charles Baudelaire, His Life",
  "author": "보들레르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-50489",
  "title": "Poems in Prose",
  "author": "보들레르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2520",
  "title": "The Man",
  "author": "브램 스토커",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-65799",
  "title": "Lady Athlyne",
  "author": "브램 스토커",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 116,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8775",
  "title": "Poems",
  "author": "빅토르 위고",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 59,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-49372",
  "title": "Ninety-Three",
  "author": "빅토르 위고",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-652",
  "title": "Rasselas, Prince of Abyssinia",
  "author": "새뮤얼 존슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1436",
  "title": "A Voyage to Abyssinia",
  "author": "새뮤얼 존슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-61422",
  "title": "Stories of Romance",
  "author": "새뮤얼 존슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1028",
  "title": "The Professor",
  "author": "샬럿 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 43,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-9182",
  "title": "Villette",
  "author": "샬럿 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 52,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-30486",
  "title": "Shirley",
  "author": "샬럿 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14257",
  "title": "The Magician",
  "author": "서머싯 몸",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-27063",
  "title": "The Hero",
  "author": "서머싯 몸",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-27198",
  "title": "The Explorer",
  "author": "서머싯 몸",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-31308",
  "title": "Orientations",
  "author": "서머싯 몸",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4696",
  "title": "The Witch of Atlas",
  "author": "셸리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 57,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4697",
  "title": "Peter Bell the Third",
  "author": "셸리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 58,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-10119",
  "title": "Adonais",
  "author": "셸리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-70189",
  "title": "The sensitive plant",
  "author": "셸리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-806",
  "title": "Philoktetes",
  "author": "소포클레스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 178,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7073",
  "title": "Specimens of Greek Tragedy — Aeschylus and Sophocles",
  "author": "소포클레스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-77548",
  "title": "The Philoctetes of Sophocles",
  "author": "소포클레스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-53720",
  "title": "On Love",
  "author": "스탕달",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-57638",
  "title": "The Chartreuse of Parma Translated from the French of Stendhal (Henri Beyle)",
  "author": "스탕달",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2350",
  "title": "His last bow",
  "author": "아서 코넌 도일",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 42,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2845",
  "title": "Sir Nigel",
  "author": "아서 코넌 도일",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5148",
  "title": "Rodney Stone",
  "author": "아서 코넌 도일",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-78105",
  "title": "Tales grotesque and curious",
  "author": "아쿠타가와 류노스케",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1597",
  "title": "Andersen's Fairy Tales",
  "author": "안데르센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 54,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7513",
  "title": "O. T., A Danish Romance",
  "author": "안데르센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-12313",
  "title": "Pictures of Sweden",
  "author": "안데르센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 90,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-71096",
  "title": "The nightingale",
  "author": "안데르센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1753",
  "title": "Swan Song",
  "author": "안톤 체호프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1755",
  "title": "Ivanoff: A Play",
  "author": "안톤 체호프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-23055",
  "title": "The Slanderer 1901",
  "author": "안톤 체호프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4344",
  "title": "Marie; a story of Russian love",
  "author": "알렉산드르 푸시킨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-13437",
  "title": "Best Russian Short Stories",
  "author": "알렉산드르 푸시킨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-13511",
  "title": "The Daughter of the Commandant",
  "author": "알렉산드르 푸시킨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-23058",
  "title": "The Queen Of Spades",
  "author": "알렉산드르 푸시킨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-965",
  "title": "The black tulip",
  "author": "알렉상드르 뒤마",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 184,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-41222",
  "title": "Captain Paul",
  "author": "알렉상드르 뒤마",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-66620",
  "title": "Ascanio",
  "author": "알렉상드르 뒤마",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-60914",
  "title": "Prometheus Illbound",
  "author": "앙드레 지드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-73838",
  "title": "The Vatican swindle",
  "author": "앙드레 지드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-76944",
  "title": "Dostoevsky",
  "author": "앙드레 지드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 110,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-76965",
  "title": "The counterfeiters",
  "author": "앙드레 지드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 113,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-50696",
  "title": "Railway Construction",
  "author": "어니스트 헤밍웨이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1065",
  "title": "The Raven",
  "author": "에드거 앨런 포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8893",
  "title": "Selections from Poe",
  "author": "에드거 앨런 포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 60,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-21964",
  "title": "The Short-story",
  "author": "에드거 앨런 포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7011",
  "title": "The Flood",
  "author": "에밀 졸라",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8558",
  "title": "L'Assommoir",
  "author": "에밀 졸라",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 58,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-9499",
  "title": "The Dream",
  "author": "에밀 졸라",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 63,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-56528",
  "title": "Germinal",
  "author": "에밀 졸라",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2678",
  "title": "Poems by Emily Dickinson, Series One",
  "author": "에밀리 디킨슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 55,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2679",
  "title": "Poems by Emily Dickinson, Series Two",
  "author": "에밀리 디킨슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 56,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-12241",
  "title": "Poems by Emily Dickinson, Third Series",
  "author": "에밀리 디킨슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 90,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-12242",
  "title": "Poems by Emily Dickinson, Three Series, Complete",
  "author": "에밀리 디킨슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1019",
  "title": "Poems by Currer, Ellis, and Acton Bell",
  "author": "에밀리 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 43,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1583",
  "title": "Options",
  "author": "오 헨리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1595",
  "title": "Whirligigs",
  "author": "오 헨리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 52,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1728",
  "title": "The Odyssey of Homer",
  "author": "오 헨리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-62154",
  "title": "Canada",
  "author": "오 헨리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1223",
  "title": "Ursula",
  "author": "오노레 드 발자크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 40,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1437",
  "title": "Juana",
  "author": "오노레 드 발자크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1554",
  "title": "Adieu",
  "author": "오노레 드 발자크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-21920",
  "title": "The Last Poems of Ovid",
  "author": "오비디우스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-26073",
  "title": "The Metamorphoses of Ovid, Books VIII-XV",
  "author": "오비디우스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-28621",
  "title": "The Metamorphoses of Publius Ovidus Naso in English blank verse Vols. I & II",
  "author": "오비디우스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-887",
  "title": "Intentions",
  "author": "오스카 와일드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 187,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-921",
  "title": "De Profundis",
  "author": "오스카 와일드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14062",
  "title": "Miscellanies",
  "author": "오스카 와일드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 93,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14240",
  "title": "Reviews",
  "author": "오스카 와일드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4018",
  "title": "Japanese Fairy Tales",
  "author": "오자키 고요",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 45,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-41437",
  "title": "Warriors of Old Japan, and Other Stories",
  "author": "오자키 고요",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-45933",
  "title": "Romances of Old Japan Rendered into English from Japanese Sources",
  "author": "오자키 고요",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1945",
  "title": "Egmont",
  "author": "요한 볼프강 폰 괴테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2527",
  "title": "The Sorrows of Young Werther",
  "author": "요한 볼프강 폰 괴테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3023",
  "title": "Faust — Part 1",
  "author": "요한 볼프강 폰 괴테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 40,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6865",
  "title": "Four Years",
  "author": "윌리엄 버틀러 예이츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 57,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7164",
  "title": "Gitanjali",
  "author": "윌리엄 버틀러 예이츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-38877",
  "title": "Poems",
  "author": "윌리엄 버틀러 예이츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 113,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-72985",
  "title": "The tower",
  "author": "윌리엄 버틀러 예이츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-574",
  "title": "Poems of William Blake",
  "author": "윌리엄 블레이크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 180,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-45315",
  "title": "The Marriage of Heaven and Hell",
  "author": "윌리엄 블레이크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-77131",
  "title": "Drug themes in science fiction",
  "author": "윌리엄 블레이크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14952",
  "title": "Selections from Wordsworth and Tennyson",
  "author": "윌리엄 워즈워스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-61587",
  "title": "The Old Church Clock",
  "author": "윌리엄 워즈워스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-76806",
  "title": "The law of copyright",
  "author": "윌리엄 워즈워스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-52515",
  "title": "The White Elephant, and Other Tales From India",
  "author": "윌리엄 포크너",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-69416",
  "title": "Christmas stories",
  "author": "윌리엄 포크너",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4015",
  "title": "The Hairy Ape",
  "author": "유진 오닐",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 42,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4025",
  "title": "Anna Christie",
  "author": "유진 오닐",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 43,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-22638",
  "title": "The Straw",
  "author": "유진 오닐",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-72442",
  "title": "Gold",
  "author": "유진 오닐",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-166",
  "title": "Summer",
  "author": "이디스 워튼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-283",
  "title": "The Reef",
  "author": "이디스 워튼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-24131",
  "title": "Xingu",
  "author": "이디스 워튼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-55807",
  "title": "Verses",
  "author": "이디스 워튼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2466",
  "title": "Virgin Soil",
  "author": "이반 세르게예비치 투르게네프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5721",
  "title": "A House of Gentlefolk",
  "author": "이반 세르게예비치 투르게네프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6900",
  "title": "Rudin: A Novel",
  "author": "이반 세르게예비치 투르게네프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-40813",
  "title": "Smoke",
  "author": "이반 세르게예비치 투르게네프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-28",
  "title": "The Fables of Aesop Selected, Told Anew, and Their History Traced",
  "author": "이솝",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 126,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-11339",
  "title": "Aesop's Fables; a new translation",
  "author": "이솝",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-25433",
  "title": "The Baby's Own Aesop",
  "author": "이솝",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-53103",
  "title": "Æsop's Fables",
  "author": "이솝",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1160",
  "title": "The Game",
  "author": "잭 런던",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 40,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1163",
  "title": "Adventure",
  "author": "잭 런던",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 43,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14658",
  "title": "The Road",
  "author": "잭 런던",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-44744",
  "title": "Superstition in Medicine",
  "author": "제롬 데이비드 샐린저",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-105",
  "title": "Persuasion",
  "author": "제인 오스틴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 170,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2817",
  "title": "Chamber Music",
  "author": "제임스 조이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4300",
  "title": "Ulysses",
  "author": "제임스 조이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 39,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-55945",
  "title": "Exiles: A Play in Three Acts",
  "author": "제임스 조이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-257",
  "title": "Troilus and Criseyde",
  "author": "제프리 초서",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 178,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2383",
  "title": "The Canterbury Tales, and Other Poems",
  "author": "제프리 초서",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-7490",
  "title": "Dryden's Palamon and Arcite",
  "author": "제프리 초서",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 52,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-78062",
  "title": "The flower and the leaf",
  "author": "제프리 초서",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3726",
  "title": "The Decameron, Volume I",
  "author": "조반니 보카치오",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-10006",
  "title": "La Fiammetta",
  "author": "조반니 보카치오",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 87,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-13102",
  "title": "The Decameron, Volume II",
  "author": "조반니 보카치오",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 87,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-23700",
  "title": "The Decameron of Giovanni Boccaccio",
  "author": "조반니 보카치오",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5131",
  "title": "Childe Harold's Pilgrimage",
  "author": "조지 고든 바이런",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 42,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-15368",
  "title": "Fugitive Pieces",
  "author": "조지 고든 바이런",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-21700",
  "title": "Don Juan",
  "author": "조지 고든 바이런",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 90,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-32990",
  "title": "A Day with Lord Byron",
  "author": "조지 고든 바이런",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-507",
  "title": "Adam Bede",
  "author": "조지 엘리엇",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6688",
  "title": "The Mill on the Floss",
  "author": "조지 엘리엇",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 60,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-24020",
  "title": "Romola",
  "author": "조지 엘리엇",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 88,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1142",
  "title": "Typhoon",
  "author": "조지프 콘래드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 40,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2021",
  "title": "Nostromo: A Tale of the Seaboard",
  "author": "조지프 콘래드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 37,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-23772",
  "title": "Devotions Upon Emergent Occasions; Together with Death's Duel",
  "author": "존 단",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-37387",
  "title": "Letters to Severall Persons of Honour",
  "author": "존 단",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-61783",
  "title": "Paradoxes and Problemes With two characters and an essay of valour. Now for the first time reprinted from the editions of 1633 and 1652 with one additional probleme.",
  "author": "존 단",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2490",
  "title": "Lamia",
  "author": "존 키츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8209",
  "title": "Poems 1817",
  "author": "존 키츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-24280",
  "title": "Endymion: A Poetic Romance",
  "author": "존 키츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-30451",
  "title": "A Day with Keats",
  "author": "존 키츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 93,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-580",
  "title": "The Pickwick Papers",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-766",
  "title": "David Copperfield",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 183,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-968",
  "title": "Martin Chuzzlewit",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 187,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5616",
  "title": "The Madman: His Parables and Poems",
  "author": "칼릴 지브란",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 50,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-55500",
  "title": "Twenty Drawings",
  "author": "칼릴 지브란",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-58585",
  "title": "The Prophet",
  "author": "칼릴 지브란",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-696",
  "title": "The Castle of Otranto",
  "author": "퀸투스 호라티우스 플라쿠스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 185,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14098",
  "title": "Hieroglyphic Tales",
  "author": "퀸투스 호라티우스 플라쿠스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-34766",
  "title": "Shorter novels, vol. 3",
  "author": "퀸투스 호라티우스 플라쿠스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-19188",
  "title": "Poems",
  "author": "크리스티나 로세티",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-76703",
  "title": "Sing-song",
  "author": "크리스티나 로세티",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-77809",
  "title": "Verses",
  "author": "크리스티나 로세티",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6524",
  "title": "Stray Birds",
  "author": "타고르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-40766",
  "title": "Nationalism",
  "author": "타고르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-47813",
  "title": "Normandy",
  "author": "토마스 만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-61284",
  "title": "Bashan and I",
  "author": "토마스 만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-76837",
  "title": "Three essays",
  "author": "토마스 만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-482",
  "title": "The Woodlanders",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 178,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3056",
  "title": "Wessex Tales",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3146",
  "title": "Two on a Tower",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-18269",
  "title": "Pascal's Pensées",
  "author": "파스칼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 106,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-46921",
  "title": "The Thoughts of Blaise Pascal",
  "author": "파스칼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8117",
  "title": "The possessed",
  "author": "표도르 도스토옙스키",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-19322",
  "title": "The Antichrist",
  "author": "프리드리히 니체",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-39955",
  "title": "The Dawn of Day",
  "author": "프리드리히 니체",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 111,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2782",
  "title": "Wilhelm Tell",
  "author": "프리드리히 실러",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5637",
  "title": "Literary and Philosophical Essays: French, German and Italian",
  "author": "프리드리히 실러",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 53,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2500",
  "title": "Siddhartha",
  "author": "헤르만 헤세",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 39,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-74222",
  "title": "Demian",
  "author": "헤르만 헤세",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "coverSrc": "./covers/gb-74222.webp",
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-75756",
  "title": "Steppenwolf",
  "author": "헤르만 헤세",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 110,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1022",
  "title": "Walking",
  "author": "헨리 데이비드 소로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 37,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-9846",
  "title": "Excursions",
  "author": "헨리 데이비드 소로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 59,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-34392",
  "title": "Cape Cod",
  "author": "헨리 데이비드 소로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1195",
  "title": "Glasses",
  "author": "헨리 제임스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2299",
  "title": "Pandora",
  "author": "헨리 제임스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 54,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2542",
  "title": "A Doll's House : a play",
  "author": "헨리크 입센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 45,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-8121",
  "title": "Ghosts",
  "author": "헨리크 입센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-15492",
  "title": "A Doll's House",
  "author": "헨리크 입센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-10546",
  "title": "So Runs the World",
  "author": "헨릭 시엔키에비츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-36583",
  "title": "Hania",
  "author": "헨릭 시엔키에비츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-46454",
  "title": "In Vain",
  "author": "헨릭 시엔키에비츠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 }
];
