// 해외 고전 — 북스타 등록 데이터 (자동생성: 클레버/_final_foreign.py)
// hasTrans=bodies_*.js 존재 자동판정, coverSrc=covers/*.webp 존재 자동판정 (하드코딩 없음)
// 본문=Supabase classics(origin='foreign') fetch(id=gb-{gutenberg_id})
// 총 150권 (번역 107 / 표지 107)
const BOOKS_CLASSICS_FOREIGN = [
 {
  "id": "gb-2701",
  "title": "Moby Dick; Or, The Whale",
  "author": "허먼 멜빌",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 42,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2701.webp"
 },
 {
  "id": "gb-1342",
  "title": "Pride and Prejudice",
  "author": "제인 오스틴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 42,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1342.webp"
 },
 {
  "id": "gb-84",
  "title": "Frankenstein; or, the modern prometheus",
  "author": "메리 셸리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 128,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-84.webp"
 },
 {
  "id": "gb-1184",
  "title": "The Count of Monte Cristo",
  "author": "알렉상드르 뒤마; 오귀스트 마케",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2554",
  "title": "Crime and Punishment",
  "author": "표도르 도스토옙스키",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2554.webp"
 },
 {
  "id": "gb-11",
  "title": "Alice's Adventures in Wonderland",
  "author": "루이스 캐럴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 118,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-11.webp"
 },
 {
  "id": "gb-145",
  "title": "Middlemarch",
  "author": "조지 엘리엇",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1260",
  "title": "Jane Eyre: An Autobiography",
  "author": "샬럿 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1260.webp"
 },
 {
  "id": "gb-37106",
  "title": "Little Women; Or, Meg, Jo, Beth, and Amy",
  "author": "루이자 메이 올컷",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-37106.webp"
 },
 {
  "id": "gb-43",
  "title": "The strange case of Dr. Jekyll and Mr. Hyde",
  "author": "로버트 루이스 스티븐슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 123,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-43.webp"
 },
 {
  "id": "gb-345",
  "title": "Dracula",
  "author": "브램 스토커",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-345.webp"
 },
 {
  "id": "gb-64317",
  "title": "The Great Gatsby",
  "author": "F. 스콧 피츠제럴드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-64317.webp"
 },
 {
  "id": "gb-28054",
  "title": "The Brothers Karamazov",
  "author": "표도르 도스토옙스키",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3268",
  "title": "The Mysteries of Udolpho",
  "author": "앤 래드클리프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2160",
  "title": "The Expedition of Humphry Clinker",
  "author": "토비아스 스몰릿",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-6593",
  "title": "History of Tom Jones, a Foundling",
  "author": "헨리 필딩",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 55,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-768",
  "title": "Wuthering Heights",
  "author": "에밀리 브론테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 185,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-768.webp"
 },
 {
  "id": "gb-76",
  "title": "Adventures of Huckleberry Finn",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 129,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-76.webp"
 },
 {
  "id": "gb-74",
  "title": "The Adventures of Tom Sawyer, Complete",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 127,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-74.webp"
 },
 {
  "id": "gb-98",
  "title": "A Tale of Two Cities",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 133,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-98.webp"
 },
 {
  "id": "gb-174",
  "title": "The Picture of Dorian Gray",
  "author": "오스카 와일드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-174.webp"
 },
 {
  "id": "gb-75201",
  "title": "A farewell to arms",
  "author": "어니스트 헤밍웨이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-75201.webp"
 },
 {
  "id": "gb-21839",
  "title": "Sense and Sensibility",
  "author": "제인 오스틴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-21839.webp"
 },
 {
  "id": "gb-601",
  "title": "The Monk: A Romance",
  "author": "매튜 그레고리 루이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 171,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-601.webp"
 },
 {
  "id": "gb-51252",
  "title": "The Book of the Thousand Nights and a Night — Volume 01 (of 10)",
  "author": "크레티앵 드 트루아",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2852",
  "title": "The Hound of the Baskervilles",
  "author": "아서 코난 도일",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2852.webp"
 },
 {
  "id": "gb-120",
  "title": "Treasure Island",
  "author": "로버트 루이스 스티븐슨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 167,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-120.webp"
 },
 {
  "id": "gb-468",
  "title": "Manon Lescaut",
  "author": "아베 프레보",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 182,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-468.webp"
 },
 {
  "id": "gb-564",
  "title": "The Mystery of Edwin Drood",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 179,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-564.webp"
 },
 {
  "id": "gb-2600",
  "title": "War and Peace",
  "author": "레프 톨스토이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 40,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-103",
  "title": "Around the World in Eighty Days",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 168,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-103.webp"
 },
 {
  "id": "gb-2527",
  "title": "The Sorrows of Young Werther",
  "author": "요한 볼프강 폰 괴테",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2527.webp"
 },
 {
  "id": "gb-829",
  "title": "Gulliver's Travels into Several Remote Nations of the World",
  "author": "조너선 스위프트",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 183,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-829.webp"
 },
 {
  "id": "gb-47530",
  "title": "Oliver Twist, Vol. 2 (of 3)",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-47530.webp"
 },
 {
  "id": "gb-36462",
  "title": "King Arthur and the Knights of the Round Table",
  "author": "토머스 맬러리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-36462.webp"
 },
 {
  "id": "gb-16",
  "title": "Peter Pan : [Peter and Wendy]",
  "author": "제임스 매튜 배리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 123,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-16.webp"
 },
 {
  "id": "gb-135",
  "title": "Les Misérables",
  "author": "빅토르 위고",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 173,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-135.webp"
 },
 {
  "id": "gb-18857",
  "title": "A Journey to the Centre of the Earth",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-18857.webp"
 },
 {
  "id": "gb-4300",
  "title": "Ulysses",
  "author": "제임스 조이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 39,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-86",
  "title": "A Connecticut Yankee in King Arthur's Court",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 130,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-86.webp"
 },
 {
  "id": "gb-1400",
  "title": "Great Expectations",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 37,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1400.webp"
 },
 {
  "id": "gb-5200",
  "title": "Metamorphosis",
  "author": "프란츠 카프카",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 39,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-5200.webp"
 },
 {
  "id": "gb-13951",
  "title": "Les trois mousquetaires",
  "author": "알렉상드르 뒤마; 오귀스트 마케",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-10148",
  "title": "The Merry Adventures of Robin Hood",
  "author": "하워드 파일",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-10148.webp"
 },
 {
  "id": "gb-164",
  "title": "Twenty Thousand Leagues under the Sea",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 175,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-164.webp"
 },
 {
  "id": "gb-23639",
  "title": "Plutarch's Morals",
  "author": "플루타르코스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 103,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1837",
  "title": "The Prince and the Pauper",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1837.webp"
 },
 {
  "id": "gb-45",
  "title": "Anne of Green Gables",
  "author": "루시 모드 몽고메리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 125,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-45.webp"
 },
 {
  "id": "gb-1080",
  "title": "A Modest Proposal For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick",
  "author": "조너선 스위프트",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1080.webp"
 },
 {
  "id": "gb-766",
  "title": "David Copperfield",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 183,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1399",
  "title": "Anna Karenina",
  "author": "레프 톨스토이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 54,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-57342",
  "title": "The Lives and Opinions of Eminent Philosophers",
  "author": "디오게네스 라에르티오스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 101,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-14287",
  "title": "L'île mystérieuse",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-521",
  "title": "The Life and Adventures of Robinson Crusoe",
  "author": "대니얼 디포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 172,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-521.webp"
 },
 {
  "id": "gb-215",
  "title": "The call of the wild",
  "author": "잭 런던",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 172,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-215.webp"
 },
 {
  "id": "gb-1251",
  "title": "Le Morte d'Arthur: Volume 1",
  "author": "토머스 맬러리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-5921",
  "title": "The History of Don Quixote, Volume 1, Complete",
  "author": "미겔 데 세르반테스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-25344",
  "title": "The Scarlet Letter",
  "author": "너새니얼 호손",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-25344.webp"
 },
 {
  "id": "gb-121",
  "title": "Northanger Abbey",
  "author": "제인 오스틴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 168,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-121.webp"
 },
 {
  "id": "gb-113",
  "title": "The Secret Garden",
  "author": "프랜시스 호지슨 버넷",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 169,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-113.webp"
 },
 {
  "id": "gb-203",
  "title": "Uncle Tom's Cabin",
  "author": "해리엇 비처 스토",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 169,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-203.webp"
 },
 {
  "id": "gb-2610",
  "title": "Notre-Dame de Paris",
  "author": "빅토르 위고",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 41,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-34811",
  "title": "Buddenbrooks: Verfall einer Familie",
  "author": "토마스 만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1079",
  "title": "The life and opinions of Tristram Shandy, gentleman",
  "author": "로런스 스턴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1200",
  "title": "Gargantua and Pantagruel",
  "author": "프랑수아 라블레",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 35,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-4217",
  "title": "A Portrait of the Artist as a Young Man",
  "author": "제임스 조이스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-4217.webp"
 },
 {
  "id": "gb-14838",
  "title": "The Tale of Peter Rabbit",
  "author": "베아트릭스 포터",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-14838.webp"
 },
 {
  "id": "gb-580",
  "title": "The Pickwick Papers",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-967",
  "title": "Nicholas Nickleby",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 186,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-46",
  "title": "A Christmas Carol in Prose; Being a Ghost Story of Christmas",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 126,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-46.webp"
 },
 {
  "id": "gb-21",
  "title": "Three hundred Aesop’s fables Translated by George Fyler Townsend",
  "author": "이솝",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 119,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-21.webp"
 },
 {
  "id": "gb-71865",
  "title": "Mrs. Dalloway",
  "author": "버지니아 울프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-71865.webp"
 },
 {
  "id": "gb-271",
  "title": "Black Beauty : The autobiography of a horse",
  "author": "애나 슈얼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-271.webp"
 },
 {
  "id": "gb-73",
  "title": "The Red Badge of Courage: An Episode of the American Civil War",
  "author": "스티븐 크레인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 126,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-73.webp"
 },
 {
  "id": "gb-219",
  "title": "Heart of Darkness",
  "author": "조지프 콘래드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-219.webp"
 },
 {
  "id": "gb-2833",
  "title": "The Portrait of a Lady — Volume 1",
  "author": "헨리 제임스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2833.webp"
 },
 {
  "id": "gb-1023",
  "title": "Bleak House",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 38,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-23700",
  "title": "The Decameron of Giovanni Boccaccio",
  "author": "조반니 보카치오",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 92,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-599",
  "title": "Vanity Fair",
  "author": "윌리엄 메이크피스 새커리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 187,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-500",
  "title": "The Adventures of Pinocchio",
  "author": "카를로 콜로디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 169,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-500.webp"
 },
 {
  "id": "gb-1597",
  "title": "Andersen's Fairy Tales",
  "author": "한스 크리스티안 안데르센",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 54,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1597.webp"
 },
 {
  "id": "gb-696",
  "title": "The Castle of Otranto",
  "author": "호레이스 월폴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 185,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-696.webp"
 },
 {
  "id": "gb-5225",
  "title": "The Satyricon — Complete",
  "author": "페트로니우스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 46,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-36",
  "title": "The war of the worlds",
  "author": "H. G. 웰스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 125,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-36.webp"
 },
 {
  "id": "gb-56463",
  "title": "Bacon's Essays, and Wisdom of the Ancients",
  "author": "프랜시스 베이컨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2130",
  "title": "Utopia",
  "author": "토머스 모어",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 38,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2130.webp"
 },
 {
  "id": "gb-30201",
  "title": "In Praise of Folly Illustrated with Many Curious Cuts",
  "author": "에라스무스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 86,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-30201.webp"
 },
 {
  "id": "gb-83",
  "title": "From the Earth to the moon; and, round the moon",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 127,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-83.webp"
 },
 {
  "id": "gb-110",
  "title": "Tess of the d'Urbervilles: A Pure Woman",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 166,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-110.webp"
 },
 {
  "id": "gb-10007",
  "title": "Carmilla",
  "author": "조지프 셰리든 르 파뉴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 88,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-10007.webp"
 },
 {
  "id": "gb-19942",
  "title": "Candide",
  "author": "볼테르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-19942.webp"
 },
 {
  "id": "gb-27805",
  "title": "The Wind in the Willows",
  "author": "케네스 그레이엄",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-27805.webp"
 },
 {
  "id": "gb-3526",
  "title": "Five Weeks in a Balloon Or, Journeys and Discoveries in Africa by Three Englishmen",
  "author": "쥘 베른",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 48,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-3526.webp"
 },
 {
  "id": "gb-27681",
  "title": "The Last of the Mohicans: A Narrative of 1757",
  "author": "제임스 페니모어 쿠퍼",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 104,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-27681.webp"
 },
 {
  "id": "gb-963",
  "title": "Little Dorrit",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 182,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-77",
  "title": "The House of the Seven Gables",
  "author": "너새니얼 호손",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 130,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-77.webp"
 },
 {
  "id": "gb-5658",
  "title": "Lord Jim",
  "author": "조지프 콘래드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 56,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-5658.webp"
 },
 {
  "id": "gb-968",
  "title": "Martin Chuzzlewit",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 187,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-821",
  "title": "Dombey and Son",
  "author": "찰스 디킨스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 175,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-67138",
  "title": "The Sun Also Rises",
  "author": "어니스트 헤밍웨이",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-67138.webp"
 },
 {
  "id": "gb-325",
  "title": "Phantastes: A Faerie Romance for Men and Women",
  "author": "조지 맥도널드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-325.webp"
 },
 {
  "id": "gb-1237",
  "title": "Father Goriot",
  "author": "오노레 드 발자크",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 45,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1237.webp"
 },
 {
  "id": "gb-131",
  "title": "The Pilgrim's Progress from this world to that which is to come Delivered under the similitude of a dream, by John Bunyan",
  "author": "존 버니언",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 169,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-131.webp"
 },
 {
  "id": "gb-143",
  "title": "The Mayor of Casterbridge",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 172,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-143.webp"
 },
 {
  "id": "gb-75170",
  "title": "The sound and the fury",
  "author": "윌리엄 포크너",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 100,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-52521",
  "title": "Grimm's Fairy Tales",
  "author": "야코프 그림; 빌헬름 그림 (그림 형제)",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-52521.webp"
 },
 {
  "id": "gb-2085",
  "title": "Cyropaedia: The Education of Cyrus",
  "author": "크세노폰",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 47,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2085.webp"
 },
 {
  "id": "gb-2434",
  "title": "New Atlantis",
  "author": "프랜시스 베이컨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 45,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2434.webp"
 },
 {
  "id": "gb-376",
  "title": "A Journal of the Plague Year Being Observations or Memorials of the Most Remarkable Occurrences, as Well Public as Private, Which Happened in London During the Last Great Visitation in 1665. Written by a Citizen Who Continued All the While in London",
  "author": "대니얼 디포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 180,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-376.webp"
 },
 {
  "id": "gb-122",
  "title": "The Return of the Native",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 169,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-122.webp"
 },
 {
  "id": "gb-5160",
  "title": "The Mabinogion",
  "author": "토머스 하디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-5160.webp"
 },
 {
  "id": "gb-45858",
  "title": "Lucian's True History",
  "author": "루키아노스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 110,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-45858.webp"
 },
 {
  "id": "gb-208",
  "title": "Daisy Miller: A Study",
  "author": "헨리 제임스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-208.webp"
 },
 {
  "id": "gb-4397",
  "title": "The Forsyte Saga - Complete",
  "author": "존 골즈워디",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 55,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-29021",
  "title": "The Fairy Tales of Charles Perrault",
  "author": "샤를 페로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 94,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-29021.webp"
 },
 {
  "id": "gb-2226",
  "title": "Kim",
  "author": "러디어드 키플링",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2226.webp"
 },
 {
  "id": "gb-2145",
  "title": "Ben-Hur: A tale of the Christ",
  "author": "루 월리스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 44,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-2874",
  "title": "Personal Recollections of Joan of Arc — Volume 1",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 53,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-2874.webp"
 },
 {
  "id": "gb-52006",
  "title": "Les liaisons dangereuses Lettres recueillies dans une Société et publiées pour l'instruction de quelques autres",
  "author": "쇼데를로 드 라클로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 93,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-370",
  "title": "The Fortunes and Misfortunes of the Famous Moll Flanders",
  "author": "대니얼 디포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 174,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-370.webp"
 },
 {
  "id": "gb-53489",
  "title": "The Life of Lazarillo de Tormes His Fortunes & Adversities; with a Notice of the Mendoza Family, a Short Life of the Author, Don Diego Hurtado De Mendoza, a Notice of the Work, and Some Remarks on the Character of Lazarillo de Tormes",
  "author": "작자 미상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 109,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-53489.webp"
 },
 {
  "id": "gb-33858",
  "title": "The Adventurous Simplicissimus being the description of the Life of a Strange vagabond named Melchior Sternfels von Fuchshaim",
  "author": "그리멜스하우젠",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 107,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-1666",
  "title": "The Golden Asse",
  "author": "아풀레이우스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 51,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-1666.webp"
 },
 {
  "id": "gb-48529",
  "title": "Essais de Montaigne (self-édition) - Volume I",
  "author": "미셸 드 몽테뉴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 108,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-9611",
  "title": "Joseph Andrews, Vol. 1",
  "author": "헨리 필딩",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-9611.webp"
 },
 {
  "id": "gb-66073",
  "title": "Death in Venice",
  "author": "토마스 만",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-66073.webp"
 },
 {
  "id": "gb-913",
  "title": "A Hero of Our Time",
  "author": "미하일 레르몬토프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 177,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-913.webp"
 },
 {
  "id": "gb-36151",
  "title": "Franklin's Autobiography (Eclectic English Classics)",
  "author": "벤저민 프랭클린",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-36151.webp"
 },
 {
  "id": "gb-42401",
  "title": "Vathek; An Arabian Tale",
  "author": "윌리엄 벡퍼드",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 91,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-56644",
  "title": "Bulfinch's Mythology The Age of Fable; The Age of Chivalry; Legends of Charlemagne",
  "author": "토머스 불핀치",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-3154",
  "title": "The Surprising Adventures of Baron Munchausen",
  "author": "루돌프 에리히 라스페",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 45,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-3154.webp"
 },
 {
  "id": "gb-211",
  "title": "The Aspern Papers",
  "author": "헨리 제임스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 168,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-211.webp"
 },
 {
  "id": "gb-25102",
  "title": "Nobody's boy (Sans famille)",
  "author": "엑토르 말로",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 90,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-25102.webp"
 },
 {
  "id": "gb-1565",
  "title": "The Last Days of Pompeii",
  "author": "에드워드 불워리턴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 49,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-54700",
  "title": "Oblomov",
  "author": "이반 곤차로프",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 96,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-54700.webp"
 },
 {
  "id": "gb-76513",
  "title": "Billy Budd : and other prose pieces",
  "author": "허먼 멜빌",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 102,
  "reviews": 22,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-76513.webp"
 },
 {
  "id": "gb-804",
  "title": "A Sentimental Journey Through France and Italy",
  "author": "로런스 스턴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-804.webp"
 },
 {
  "id": "gb-41659",
  "title": "The Swiss Family Robinson: A Translation from the Original German",
  "author": "요한 다비드 비스",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-41659.webp"
 },
 {
  "id": "gb-561",
  "title": "The Further Adventures of Robinson Crusoe",
  "author": "대니얼 디포",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 176,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-561.webp"
 },
 {
  "id": "gb-9198",
  "title": "The Complete Angler 1653",
  "author": "아이작 월턴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 59,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-9198.webp"
 },
 {
  "id": "gb-69768",
  "title": "The bridge of San Luis Rey",
  "author": "손턴 와일더",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 116,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-69768.webp"
 },
 {
  "id": "gb-15711",
  "title": "Frau Bovary",
  "author": "귀스타브 플로베르",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-15711.webp"
 },
 {
  "id": "gb-57052",
  "title": "Röda rummet: Skildringar ur artist- och författarlivet",
  "author": "아우구스트 스트린드베리",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 99,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-597",
  "title": "The Story of Burnt Njal: The Great Icelandic Tribune, Jurist, and Counsellor",
  "author": "작자 미상",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 185,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "gb-64636",
  "title": "Rip Van Winkle",
  "author": "워싱턴 어빙",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 105,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-64636.webp"
 },
 {
  "id": "gb-23058",
  "title": "The Queen Of Spades",
  "author": "알렉산드르 푸시킨",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 98,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-23058.webp"
 },
 {
  "id": "gb-50109",
  "title": "The Mysterious Stranger: A Romance",
  "author": "마크 트웨인",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 95,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-50109.webp"
 },
 {
  "id": "gb-158",
  "title": "Emma",
  "author": "제인 오스틴",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 178,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-158.webp"
 },
 {
  "id": "gb-74222",
  "title": "Demian",
  "author": "헤르만 헤세",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": true,
  "src": "Gutenberg",
  "participants": 97,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/gb-74222.webp"
 },
 {
  "id": "gb-82",
  "title": "Ivanhoe",
  "author": "월터 스콧",
  "category": "해외문학",
  "period": "해외",
  "locale": "foreign",
  "intl": false,
  "hasBody": true,
  "hasTrans": false,
  "src": "Gutenberg",
  "participants": 126,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 }
];
