// 한국 고전 110권 — 북스타 등록 데이터 (자동생성: 클레버/_gen_classics_kr_data.py)
// 표지=제목만(텍스트), 본문=Supabase classics 테이블 fetch(id=kr-작가-작품)
// 총 110권
const BOOKS_CLASSICS_KR = [
 {
  "id": "kr-강경애-소금",
  "coverSrc": "./covers/kr-sogeum.webp",
  "title": "소금",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 137,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-강경애-어머니와-딸",
  "coverSrc": "./covers/kr-eomeoniwattal.webp",
  "title": "어머니와 딸",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 97,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-강경애-원고료-이백-원",
  "coverSrc": "./covers/kr-wongoryoibaekwon.webp",
  "title": "원고료 이백 원",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 148,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-강경애-인간-문제",
  "coverSrc": "./covers/kr-inganmunje.webp",
  "title": "인간 문제",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 59,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-강경애-지하촌",
  "coverSrc": "./covers/kr-jihachon.webp",
  "title": "지하촌",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 41,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-강경애-파금",
  "coverSrc": "./covers/kr-pageum.webp",
  "title": "파금",
  "author": "강경애",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 167,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김남천-경영",
  "coverSrc": "./covers/kr-gyeongyeong.webp",
  "title": "경영",
  "author": "김남천",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 126,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김남천-대하",
  "coverSrc": "./covers/kr-daeha.webp",
  "title": "대하",
  "author": "김남천",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 87,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김남천-맥",
  "coverSrc": "./covers/kr-maek.webp",
  "title": "맥",
  "author": "김남천",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 73,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김남천-물",
  "coverSrc": "./covers/kr-mul.webp",
  "title": "물",
  "author": "김남천",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 58,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김남천-소년행",
  "coverSrc": "./covers/kr-sonyeonhaeng.webp",
  "title": "소년행",
  "author": "김남천",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 164,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-K박사의-연구",
  "coverSrc": "./covers/kr-kbaksauiyeongu.webp",
  "title": "K박사의 연구",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 180,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-감자",
  "coverSrc": "./covers/kr-gamja.webp",
  "title": "감자",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 52,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-광염소나타",
  "coverSrc": "./covers/kr-gwangyeomsonata.webp",
  "title": "광염소나타",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 63,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-광화사",
  "coverSrc": "./covers/kr-gwanghwasa.webp",
  "title": "광화사",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 116,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-마음이-옅은-자여",
  "coverSrc": "./covers/kr-maeumiyeoteunjayeo.webp",
  "title": "마음이 옅은 자여",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 162,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-명문",
  "coverSrc": "./covers/kr-myeongmun.webp",
  "title": "명문",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 164,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-무지개",
  "coverSrc": "./covers/kr-mujigae.webp",
  "title": "무지개",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 112,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-발가락이-닮았다",
  "coverSrc": "./covers/kr-balgarakidalmassda.webp",
  "title": "발가락이 닮았다",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 106,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-배따라기",
  "title": "배따라기",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 110,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/kr-baettaragi.webp?v=3"
 },
 {
  "id": "kr-김동인-붉은-산",
  "title": "붉은 산",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "coverSrc": "./covers/kr-bulgeunsan.webp",
  "src": "공유마당",
  "participants": 50,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-시골-황서방",
  "coverSrc": "./covers/kr-sigolhwangseobang.webp",
  "title": "시골 황서방",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 79,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-약한-자의-슬픔",
  "coverSrc": "./covers/kr-yakhanjauiseulpeum.webp",
  "title": "약한 자의 슬픔",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 90,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-젊은-그들",
  "coverSrc": "./covers/kr-jeolmeungeudeul.webp",
  "title": "젊은 그들",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 168,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-죽음",
  "coverSrc": "./covers/kr-jukeum.webp",
  "title": "죽음",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 35,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김동인-태형",
  "coverSrc": "./covers/kr-taehyeong.webp",
  "title": "태형",
  "author": "김동인",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 167,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-김소월-김소월-시선",
  "title": "김소월 시선",
  "author": "김소월",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 175,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/kr-kimsowol-poems.webp"
 },
 {
  "id": "kr-김영랑-김영랑-시선",
  "coverSrc": "./covers/kr-gimyeongrangsiseon.webp",
  "title": "김영랑 시선",
  "author": "김영랑",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 168,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나도향-물레방아",
  "coverSrc": "./covers/kr-mulrebanga.webp",
  "title": "물레방아",
  "author": "나도향",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 122,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나도향-벙어리-삼룡이",
  "coverSrc": "./covers/kr-beongeorisamryongi.webp",
  "title": "벙어리 삼룡이",
  "author": "나도향",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 141,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나도향-별을-안거든",
  "coverSrc": "./covers/kr-byeoleulangeodeun.webp",
  "title": "별을 안거든",
  "author": "나도향",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 152,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나도향-뽕",
  "coverSrc": "./covers/kr-ppong.webp",
  "title": "뽕",
  "author": "나도향",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 129,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나도향-행랑-자식",
  "coverSrc": "./covers/kr-haengrangjasik.webp",
  "title": "행랑 자식",
  "author": "나도향",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 164,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나혜석-경희",
  "coverSrc": "./covers/kr-gyeonghui.webp",
  "title": "경희",
  "author": "나혜석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 39,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-나혜석-규원",
  "coverSrc": "./covers/kr-gyuwon.webp",
  "title": "규원",
  "author": "나혜석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 96,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-박용철-박용철-시선",
  "coverSrc": "./covers/kr-bakyongcheolsiseon.webp",
  "title": "박용철 시선",
  "author": "박용철",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 18,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-신채호-꿈하늘",
  "coverSrc": "./covers/kr-kkumhaneul.webp",
  "title": "꿈하늘",
  "author": "신채호",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 87,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-신채호-백세-노승의-미인담",
  "coverSrc": "./covers/kr-baeksenoseunguimiindam.webp",
  "title": "백세 노승의 미인담",
  "author": "신채호",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 107,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-신채호-용과-용의-대격전",
  "coverSrc": "./covers/kr-yonggwayonguidaegyeokjeon.webp",
  "title": "용과 용의 대격전",
  "author": "신채호",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 22,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-신채호-을지문덕",
  "coverSrc": "./covers/kr-euljimundeok.webp",
  "title": "을지문덕",
  "author": "신채호",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 51,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-신채호-이순신",
  "coverSrc": "./covers/kr-isunsin.webp",
  "title": "이순신",
  "author": "신채호",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 177,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-오장환-오장환-시선",
  "coverSrc": "./covers/kr-ojanghwansiseon.webp",
  "title": "오장환 시선",
  "author": "오장환",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 68,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-가실",
  "coverSrc": "./covers/kr-gasil.webp",
  "title": "가실",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 162,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-단종애사",
  "coverSrc": "./covers/kr-danjongaesa.webp",
  "title": "단종애사",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 177,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-마의태자",
  "coverSrc": "./covers/kr-mauitaeja.webp",
  "title": "마의태자",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 74,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-무정",
  "coverSrc": "./covers/kr-mujeong.webp",
  "title": "무정",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 53,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-사랑",
  "coverSrc": "./covers/kr-sarang.webp",
  "title": "사랑",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 163,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-원효대사",
  "coverSrc": "./covers/kr-wonhyodaesa.webp",
  "title": "원효대사",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 130,
  "reviews": 7,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-유정",
  "coverSrc": "./covers/kr-yujeong.webp",
  "title": "유정",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 176,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-이차돈의-사",
  "coverSrc": "./covers/kr-ichadonuisa.webp",
  "title": "이차돈의 사",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 26,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이광수-재생",
  "coverSrc": "./covers/kr-jaesaeng.webp",
  "title": "재생",
  "author": "이광수",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 144,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이무영-산가",
  "coverSrc": "./covers/kr-sanga.webp",
  "title": "산가",
  "author": "이무영",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 160,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이무영-제1과-제1장",
  "coverSrc": "./covers/kr-je1gwaje1jang.webp",
  "title": "제1과 제1장",
  "author": "이무영",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 81,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이무영-흙의-노예",
  "coverSrc": "./covers/kr-heulkuinoye.webp",
  "title": "흙의 노예",
  "author": "이무영",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 87,
  "reviews": 0,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-12월-12일",
  "coverSrc": "./covers/kr-12wol12il.webp",
  "title": "12월 12일",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 73,
  "reviews": 6,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-권태",
  "coverSrc": "./covers/kr-gwontae.webp",
  "title": "권태",
  "author": "이상",
  "category": "수필",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 63,
  "reviews": 24,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-날개",
  "title": "날개",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 124,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0,
  "coverSrc": "./covers/kr-nalgae.webp?v=3"
 },
 {
  "id": "kr-이상-동해",
  "coverSrc": "./covers/kr-donghae.webp",
  "title": "동해",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 140,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-봉별기",
  "coverSrc": "./covers/kr-bongbyeolgi.webp",
  "title": "봉별기",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "위키문헌",
  "participants": 102,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-이상-시선(오감도·거울·역단·위독)",
  "coverSrc": "./covers/kr-isangsiseonogamdogeoulyeokdanwidok.webp",
  "title": "이상 시선(오감도·거울·역단·위독)",
  "author": "이상",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 94,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-종생기",
  "coverSrc": "./covers/kr-jongsaenggi.webp",
  "title": "종생기",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 66,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상-지주회시",
  "coverSrc": "./covers/kr-jijuhoesi.webp",
  "title": "지주회시",
  "author": "이상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "위키문헌",
  "participants": 137,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이상화-이상화-시선",
  "coverSrc": "./covers/kr-isanghwasiseon.webp",
  "title": "이상화 시선",
  "author": "이상화",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 143,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이육사-이육사-시선",
  "coverSrc": "./covers/kr-iyuksasiseon.webp",
  "title": "이육사 시선",
  "author": "이육사",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 98,
  "reviews": 10,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이익상-광란",
  "coverSrc": "./covers/kr-gwangran.webp",
  "title": "광란",
  "author": "이익상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 31,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이익상-쫓기어-가는-이들",
  "coverSrc": "./covers/kr-jjochgieoganeunideul.webp",
  "title": "쫓기어 가는 이들",
  "author": "이익상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 14,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이익상-흙의-세례",
  "coverSrc": "./covers/kr-heulkuiserye.webp",
  "title": "흙의 세례",
  "author": "이익상",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 178,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-개살구",
  "coverSrc": "./covers/kr-gaesalgu.webp",
  "title": "개살구",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 53,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-노령근해",
  "coverSrc": "./covers/kr-noryeonggeunhae.webp",
  "title": "노령근해",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 128,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-도시와-유령",
  "coverSrc": "./covers/kr-dosiwayuryeong.webp",
  "title": "도시와 유령",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 98,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-돈",
  "coverSrc": "./covers/kr-don.webp",
  "title": "돈",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 121,
  "reviews": 24,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-들",
  "coverSrc": "./covers/kr-deul.webp",
  "title": "들",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 56,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-메밀꽃-필-무렵",
  "title": "메밀꽃 필 무렵",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "coverSrc": "./covers/kr-memilkkot.webp",
  "src": "공유마당",
  "participants": 172,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-분녀",
  "coverSrc": "./covers/kr-bunnyeo.webp",
  "title": "분녀",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 146,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-산",
  "coverSrc": "./covers/kr-san.webp",
  "title": "산",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 127,
  "reviews": 24,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-수탉",
  "coverSrc": "./covers/kr-sutalk.webp",
  "title": "수탉",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 91,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-장미-병들다",
  "coverSrc": "./covers/kr-jangmibyeongdeulda.webp",
  "title": "장미 병들다",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 153,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-이효석-화분",
  "coverSrc": "./covers/kr-hwabun.webp",
  "title": "화분",
  "author": "이효석",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 153,
  "reviews": 23,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-임화-임화-시선",
  "coverSrc": "./covers/kr-imhwasiseon.webp",
  "title": "임화 시선",
  "author": "임화",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 19,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-정지용-정지용-시선",
  "coverSrc": "./covers/kr-jeongjiyongsiseon.webp",
  "title": "정지용 시선",
  "author": "정지용",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 78,
  "reviews": 17,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-논-이야기",
  "coverSrc": "./covers/kr-noniyagi.webp",
  "title": "논 이야기",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 80,
  "reviews": 11,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-동화",
  "coverSrc": "./covers/kr-donghwa.webp",
  "title": "동화",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 126,
  "reviews": 12,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-두-순정",
  "coverSrc": "./covers/kr-dusunjeong.webp",
  "title": "두 순정",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 21,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-레디메이드",
  "coverSrc": "./covers/kr-redimeideu.webp",
  "title": "레디메이드",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 67,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-명일",
  "coverSrc": "./covers/kr-myeongil.webp",
  "title": "명일",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 44,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-미스터-방",
  "coverSrc": "./covers/kr-miseuteobang.webp",
  "title": "미스터 방",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 144,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-소망",
  "coverSrc": "./covers/kr-somang.webp",
  "title": "소망",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 146,
  "reviews": 2,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-쑥국새",
  "coverSrc": "./covers/kr-ssukguksae.webp",
  "title": "쑥국새",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 104,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-이런-처지",
  "coverSrc": "./covers/kr-ireoncheoji.webp",
  "title": "이런 처지",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 37,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-정자나무-있는-삽화",
  "coverSrc": "./covers/kr-jeongjanamuissneunsabhwa.webp",
  "title": "정자나무 있는 삽화",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 90,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-치숙",
  "coverSrc": "./covers/kr-chisuk.webp",
  "title": "치숙",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 80,
  "reviews": 13,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-탁류",
  "coverSrc": "./covers/kr-takryu.webp",
  "title": "탁류",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 87,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-채만식-태평천하",
  "coverSrc": "./covers/kr-taepyeongcheonha.webp",
  "title": "태평천하",
  "author": "채만식",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 172,
  "reviews": 14,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-그믐밤",
  "coverSrc": "./covers/kr-geumeumbam.webp",
  "title": "그믐밤",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 146,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-기아와-살육",
  "coverSrc": "./covers/kr-giawasalyuk.webp",
  "title": "기아와 살육",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 22,
  "reviews": 16,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-박돌",
  "coverSrc": "./covers/kr-bakdol.webp",
  "title": "박돌",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 73,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-큰물-진-뒤",
  "coverSrc": "./covers/kr-keunmuljindwi.webp",
  "title": "큰물 진 뒤",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 21,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-탈출기",
  "coverSrc": "./covers/kr-talchulgi.webp",
  "title": "탈출기",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 125,
  "reviews": 9,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-최서해-홍염",
  "coverSrc": "./covers/kr-hongyeom.webp",
  "title": "홍염",
  "author": "최서해",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 40,
  "reviews": 21,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-한용운-한용운-시선",
  "coverSrc": "./covers/kr-hanyongunsiseon.webp",
  "title": "한용운 시선",
  "author": "한용운",
  "category": "시",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 95,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-B사감",
  "coverSrc": "./covers/kr-bsagam.webp",
  "title": "B사감",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 129,
  "reviews": 5,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-고향",
  "coverSrc": "./covers/kr-gohyang.webp",
  "title": "고향",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 81,
  "reviews": 1,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-불",
  "coverSrc": "./covers/kr-bul.webp",
  "title": "불",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 160,
  "reviews": 24,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-빈처",
  "coverSrc": "./covers/kr-bincheo.webp",
  "title": "빈처",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 113,
  "reviews": 4,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-술-권하는-사회",
  "coverSrc": "./covers/kr-sulgwonhaneunsahoe.webp",
  "title": "술 권하는 사회",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 117,
  "reviews": 20,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-운수-좋은-날",
  "title": "운수 좋은 날",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "coverSrc": "./covers/kr-unsujoeunnal.webp",
  "src": "공유마당",
  "participants": 69,
  "reviews": 15,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-타락자",
  "coverSrc": "./covers/kr-tarakja.webp",
  "title": "타락자",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 53,
  "reviews": 18,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-피아노",
  "coverSrc": "./covers/kr-piano.webp",
  "title": "피아노",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": true,
  "src": "공유마당",
  "participants": 128,
  "reviews": 3,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-할머니의-죽음",
  "coverSrc": "./covers/kr-halmeoniuijukeum.webp",
  "title": "할머니의 죽음",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 86,
  "reviews": 19,
  "quizzes": 5,
  "progress": 0
 },
 {
  "id": "kr-현진건-희생화",
  "coverSrc": "./covers/kr-huisaenghwa.webp",
  "title": "희생화",
  "author": "현진건",
  "category": "소설",
  "period": "근대",
  "locale": "modern",
  "intl": true,
  "hasBody": true,
  "hasTrans": false,
  "src": "공유마당",
  "participants": 179,
  "reviews": 8,
  "quizzes": 5,
  "progress": 0
 }
];
